name: Build and push image

on: 
  push:
    branch: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build docker images
        run : docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/reaction

      - name: push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/reaction

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: log in to ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: moses
          IMAGE_TAG: latest,${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REPOSITORY/ECR_REPOSITORY:$IMAGE_TAG




      # - name: authenticate with ecr
      #   uses: vitr/actions-build-and-upload-to-ecs@master
      #   with:
      #     access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      #     repo: moses
      #     region: us-east-1
      #     tags: latest,${{ github.sha }}
      #     create_repo: false

    








      # -
      #   name: Login to ECR
      #   uses: aws-actions/amazon-ecr-login@v1