name: Build and push image

on: 
  push:
    branch: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build docker images
        run : docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/reaction

      - name: push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/reaction
  